### ISSUE TITLE
403 Forbidden error

### ISSUE THREAD

**Issue by jackradiance** [paulwellnerbou/grails-birt-plugin#3]
I am trying to add this plugin to my Grails 3 project, but I get this error when reloading build.gradle:

`Could not GET 'https://dl.bintray.com/paulwellnerbou/maven/org/grails/plugins/birt-report/4.3.0.4/birt-report-4.3.0.4.pom'. Received status code 403 from server: Forbidden`

**Comment by paulwellnerbou** [comment]
@jackradiance Yes, that's possible. Bintray stopped supporting free repositories, and I did not set up a new one.

I won't have time to set up a new repository for it right now -- maybe next week. So for now you'll have to build it by yourself. It will be in your local maven/gradle repository then and can be used by your application.

**Comment by jackradiance** [comment]
@paulwellnerbou thanks for your response. I cloned the repository in order to build it locally, but I had some issues:
![image](https://user-images.githubusercontent.com/94143903/162062876-e4a1ab9b-7b59-41c2-b664-8aada2d4277d.png)

Here is a screenshot of one of the errors after digging a little deeper:
![image](https://user-images.githubusercontent.com/94143903/162062613-c7fd7c46-926f-41b0-b686-ce4df733c884.png)

I tried running ./gradlew install (without the check) which created a birt report 4.4.1-SNAPSHOT plugin in my local maven repository, but this doesn't match the version number from the readme instructions. Trying to import this new local maven plugin into my Grails 5 project resulted in this error when running grails run-app:
![image](https://user-images.githubusercontent.com/94143903/162063581-046cc509-cec4-4ac3-9851-085e02ff2840.png)

org.eclipse.birt.runtime:org.eclipse.birt.runtime:4.3.0a is being compiled in the build.gradle file of your plugin code, but it throws an error.

Any help or insight you can provide would be greatly appreciated! I am upgrading the Grails version of a project that was handed to me and I'm having a hard time figuring out how to get the Birt reports to work.

**Comment by paulwellnerbou** [comment]
@jackradiance I adjusted the tests so that they run under windows, too.

Yes, of course the version is different. Just use the version you have in your repository as dependency. (Or change the version in `gradle.properties`)

**Comment by jackradiance** [comment]
@paulwellnerbou thank you! I pulled and the tests ran successfully.

I had to add http://www.it-jw.com/maven as a maven repository in my Grails 5 project in order to fix the org.eclipse.birt.runtime:org.eclipse.birt.runtime:4.3.0a plugin error.

You may want to update your readme so that it uses org.grails.plugins:birt-report:4.4.1-SNAPSHOT as the plugin name in build.gradle instead of org.grails.plugins:birt-report:4.4.0

Thanks again for your help, I was able to get my Birt reports to run successfully after a bit more debugging!
